# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5359889812548f61fe93439de5b8fc02"
name = "Oil Change Dashboard"
handle = "oil-change-dashboard-1"
application_url = "https://fossil-lab-train-fwd.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://fossil-lab-train-fwd.trycloudflare.com/auth/callback",
  "https://fossil-lab-train-fwd.trycloudflare.com/auth/shopify/callback",
  "https://fossil-lab-train-fwd.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
